    apiVersion: v1
    kind: Service
    metadata:
      name: my-app-service
    spec:
      selector:
        app: my-app
      ports:
        - protocol: TCP
          port: 80  # Внешний порт (на LoadBalancer'е)
          targetPort: 8000  # Порт бэкенда (должен совпадать с containerPort в Deployment)
      type: LoadBalancer # Или ClusterIP, NodePort - в зависимости от твоей инфраструктуры